# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["model.py"]

doc_url = "https://City-of-Helsinki.github.io/ml_project_template/"

git_url = "https://github.com/City-of-Helsinki/ml_project_template/tree/master/"

def custom_doc_links(name): return None
