# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"plot_histogram": "00_data.ipynb",
         "plot_trellis": "00_data.ipynb",
         "MachineLearningModel": "01_model.ipynb",
         "LogisticRegressionClassifier": "01_model.ipynb"}

modules = ["data.py",
           "plot.py",
           "model.py"]

doc_url = "https://NuuttiSten.github.io/ml_project_template/"

git_url = "https://github.com/NuuttiSten/ml_project_template/tree/master/"

def custom_doc_links(name): return None
