# AUTOGENERATED! DO NOT EDIT! File to edit: 00_data.ipynb (unless otherwise specified).

__all__ = []

# Cell
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets