# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ml_project_template/',
                'doc_host': 'https://City-of-Helsinki.github.io',
                'git_url': 'https://github.com/City-of-Helsinki/ml_project_template/tree/master/',
                'lib_path': 'ml_project_template'},
  'syms': { 'ml_project_template.api': {},
            'ml_project_template.data': {},
            'ml_project_template.loss': {},
            'ml_project_template.model': {},
            'ml_project_template.workflow': {}}}