# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MachineLearningModel": "01_hypotheses_space.ipynb",
         "LogisticRegressionClassifier": "01_hypotheses_space.ipynb"}

modules = ["data.py"]

doc_url = "https://NuuttiSten.github.io/ml-project-template/"

git_url = "https://github.com/NuuttiSten/ml-project-template/tree/master/"

def custom_doc_links(name): return None
